function Dashboard(){var P='bootstrap',Q='begin',R='gwt.codesvr.Dashboard=',S='gwt.codesvr=',T='Dashboard',U='startup',V='DUMMY',W=0,X=1,Y='iframe',Z='javascript:""',$='position:absolute; width:0; height:0; border:none; left: -1000px;',_=' top: -1000px;',ab='CSS1Compat',bb='<!doctype html>',cb='',db='<html><head><\/head><body><\/body><\/html>',eb='undefined',fb='DOMContentLoaded',gb=50,hb='Chrome',ib='eval("',jb='");',kb='script',lb='javascript',mb='moduleStartup',nb='moduleRequested',ob='Failed to load ',pb='head',qb='meta',rb='name',sb='Dashboard::',tb='::',ub='gwt:property',vb='content',wb='=',xb='gwt:onPropertyErrorFn',yb='Bad handler "',zb='" for "gwt:onPropertyErrorFn"',Ab='gwt:onLoadErrorFn',Bb='" for "gwt:onLoadErrorFn"',Cb='#',Db='?',Eb='/',Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='Dashboard.nocache.js',Jb='base',Kb='//',Lb='externalvisibility',Mb='internet',Nb='locale',Ob='default',Pb='locale=',Qb=7,Rb='&',Sb='__gwt_Locale',Tb='_',Ub='Unexpected exception in locale detection, using default: ',Vb=2,Wb='user.agent',Xb='webkit',Yb='safari',Zb='msie',$b=10,_b=11,ac='ie10',bc=9,cc='ie9',dc=8,ec='ie8',fc='gecko',gc='gecko1_8',hc=3,ic=4,jc='selectingPermutation',kc='Dashboard.devmode.js',lc="GWT module 'Dashboard' may need to be (re)compiled",mc=':',nc='.cache.js',oc='link',pc='rel',qc='stylesheet',rc='href',sc='loadExternalRefs',tc='CSS/Calculator.css',uc='end',vc='http:',wc='file:',xc='_gwt_dummy_',yc='__gwtDevModeHook:Dashboard',zc='Ignoring non-whitelisted Dev Mode URL: ',Ac=':moduleBase';var p=window;var q=document;s(P,Q);function r(){var a=p.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:T,sessionId:p.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
Dashboard.__sendStats=s;Dashboard.__moduleName=T;Dashboard.__errFn=null;Dashboard.__moduleBase=V;Dashboard.__softPermutationId=W;Dashboard.__computePropValue=null;Dashboard.__getPropMap=null;Dashboard.__installRunAsyncCode=function(){};Dashboard.__gwtStartLoadingFragment=function(){return null};Dashboard.__gwt_isKnownPropertyValue=function(){return false};Dashboard.__gwt_getMetaProperty=function(){return null};var t=null;var u=p.__gwt_activeModules=p.__gwt_activeModules||{};u[T]={moduleName:T};Dashboard.__moduleStartupDone=function(e){var f=u[T].bindings;u[T].bindings=function(){var a=f?f():{};var b=e[Dashboard.__softPermutationId];for(var c=W;c<b.length;c++){var d=b[c];a[d[W]]=d[X]}return a}};var v;function w(){A();return v}
function A(){if(v){return}var a=q.createElement(Y);a.src=Z;a.id=T;a.style.cssText=$+_;a.tabIndex=-1;q.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function B(k){function l(a){function b(){if(typeof q.readyState==eb){return typeof q.body!=eb&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},gb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=w();var f=e.body;var g;if(navigator.userAgent.indexOf(hb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(ib));for(var i=W;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(X,j.length-X)))}h.appendChild(e.createTextNode(jb));g=e.createElement(kb);g.language=lb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=W;i<c.length;i++){g=e.createElement(kb);g.language=lb;g.text=c[i];f.appendChild(g);d(f,g)}}}
Dashboard.onScriptDownloaded=function(a){l(function(){m(a)})};s(mb,nb);var n=q.createElement(kb);n.src=k;if(Dashboard.__errFn){n.onerror=function(){Dashboard.__errFn(T,new Error(ob+code))}}q.getElementsByTagName(pb)[W].appendChild(n)}
Dashboard.__startLoadingFragment=function(a){return F(a)};Dashboard.__installRunAsyncCode=function(a){var b=w();var c=b.body;var d=b.createElement(kb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function C(){var c={};var d;var e;var f=q.getElementsByTagName(qb);for(var g=W,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(rb),k;if(j){j=j.replace(sb,cb);if(j.indexOf(tb)>=W){continue}if(j==ub){k=i.getAttribute(vb);if(k){var l,m=k.indexOf(wb);if(m>=W){j=k.substring(W,m);l=k.substring(m+X)}else{j=k;l=cb}c[j]=l}}else if(j==xb){k=i.getAttribute(vb);if(k){try{d=eval(k)}catch(a){alert(yb+k+zb)}}}else if(j==Ab){k=i.getAttribute(vb);if(k){try{e=eval(k)}catch(a){alert(yb+k+Bb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};t=d;Dashboard.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(Cb);if(b==-1){b=a.length}var c=a.indexOf(Db);if(c==-1){c=a.length}var d=a.lastIndexOf(Eb,Math.min(c,b));return d>=W?a.substring(W,d+X):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return cb}
function h(){var a=q.getElementsByTagName(kb);for(var b=W;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return cb}
function i(){var a=q.getElementsByTagName(Jb);if(a.length>W){return a[a.length-X].href}return cb}
function j(){var a=q.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(q.location.href)}k=f(k);return k}
function F(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return Dashboard.__moduleBase+a}
function G(){var i=[];var j=W;var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(t){t(a,d,b)}throw null}
l[Lb]=function(){try{var b=__gwt_getMetaProperty(Lb);if(b==null){b=Mb}return b}catch(a){return Mb}};k[Lb]={internet:W,intranet:X};l[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=W){var f=d.substring(e+Qb);var g=d.indexOf(Rb,e);if(g<W){g=d.length}b=d.substring(e+Qb,g)}}if(!b){b=__gwt_getMetaProperty(Nb)}if(!b){b=p[Sb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Nb,b)){var h=b.lastIndexOf(Tb);if(h<W){b=null;break}b=b.substring(W,h)}}catch(a){alert(Ub+a)}p[Sb]=c;return b||Ob};k[Nb]={'default':W,en_US:X,tr:Vb};l[Wb]=function(){var a=navigator.userAgent.toLowerCase();var b=q.documentMode;if(function(){return a.indexOf(Xb)!=-1}())return Yb;if(function(){return a.indexOf(Zb)!=-1&&(b>=$b&&b<_b)}())return ac;if(function(){return a.indexOf(Zb)!=-1&&(b>=bc&&b<_b)}())return cc;if(function(){return a.indexOf(Zb)!=-1&&(b>=dc&&b<_b)}())return ec;if(function(){return a.indexOf(fc)!=-1||b>=_b}())return gc;return cb};k[Wb]={gecko1_8:W,ie10:X,ie8:Vb,ie9:hc,safari:ic};__gwt_isKnownPropertyValue=function(a,b){return b in k[a]};Dashboard.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};Dashboard.__computePropValue=m;p.__gwt_activeModules[T].bindings=Dashboard.__getPropMap;s(P,jc);if(r()){return F(kc)}var n;try{alert(lc);return;var o=n.indexOf(mc);if(o!=-1){j=parseInt(n.substring(o+X),$b);n=n.substring(W,o)}}catch(a){}Dashboard.__softPermutationId=j;return F(n+nc)}
function H(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=q.createElement(oc);b.setAttribute(pc,qc);b.setAttribute(rc,F(a));q.getElementsByTagName(pb)[W].appendChild(b);__gwt_stylesLoaded[a]=true}}
s(sc,Q);c(tc);s(sc,uc)}
C();Dashboard.__moduleBase=D();u[T].moduleBase=Dashboard.__moduleBase;var I=G();if(p){var J=!!(p.location.protocol==vc||p.location.protocol==wc);p.__gwt_activeModules[T].canRedirect=J;function K(){var b=xc;try{p.sessionStorage.setItem(b,b);p.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(J&&K()){var L=yc;var M=p.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(zc+M)}M=cb}if(M&&!p[L]){p[L]=true;p[L+Ac]=D();var N=q.createElement(kb);N.src=M;var O=q.getElementsByTagName(pb)[W];O.insertBefore(N,O.firstElementChild||O.children[W]);return false}}}H();s(P,uc);B(I);return true}
Dashboard.succeeded=Dashboard();